### ISSUE TITLE
flutter run problem

### ISSUE THREAD

**Issue by seleznova** [seleznova/flutter#1]
Ubuntu 16.04
IntelliJ Idea

```
flutter run
Launching lib/main.dart on TegraNote P1640 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/app-debug.apk (21.2MB).
Unhandled exception:
Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8108/ws
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:738)
<asynchronous suspension>
#2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:566)
<asynchronous suspension>
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:414)
<asynchronous suspension>
#4      VMService.getVM (package:flutter_tools/src/vmservice.dart:243)
#5      FlutterDevice.getVMs (package:flutter_tools/src/resident_runner.dart:81)
<asynchronous suspension>
#6      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:543)
<asynchronous suspension>
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:106)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:206)
<asynchronous suspension>
#9      AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:413)
<asynchronous suspension>
#10     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#11     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1467)
#15     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#16     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:769)
#17     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:411)
<asynchronous suspension>
#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:260)
<asynchronous suspension>
#19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:220)
<asynchronous suspension>
#20     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:227)
<asynchronous suspension>
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#22     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#28     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#29     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#30     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#31     _rootRun (dart:async/zone.dart:1120)
#32     _CustomZone.run (dart:async/zone.dart:1001)
#33     runZoned (dart:async/zone.dart:1467)
#34     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#35     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#36     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#37     main (file:///home/mary/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

**Comment by seleznova** [comment]
```
mary@seleznova:~/flutter/myapp$ flutter doctor
[✓] Flutter (on Linux, locale en_GB.UTF-8, channel alpha)
    • Flutter at /home/mary/flutter/flutter
    • Framework revision bbcfb8d51a (4 days ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/mary/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[✓] Connected devices
    • TegraNote P1640 • 0521014104468001B795 • android-arm • Android 5.1 (API 22)

```

**Comment by seleznova** [comment]
What helped me to run an app:

mary@seleznova:~/flutter$ sudo -s
root@seleznova:~/flutter# export PATH=`pwd`/flutter/bin:$PATH
root@seleznova:~/flutter# cd myapp/
root@seleznova:~/flutter/myapp# flutter run
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Launching lib/main.dart on TegraNote P1640 in debug mode...
Initializing gradle...                                2.4s
Resolving dependencies...                            75.7s
Running 'gradlew assembleDebug'...                    8.7s
Built build/app/outputs/apk/app-debug.apk (21.2MB).
Installing build/app/outputs/apk/app.apk...          16.4s
Error connecting to the service protocol: TimeoutException: Request to Dart VM Service timed out: _flutter.listViews({})

**Comment by seleznova** [comment]
Actually, the problem is related with Dart VM and I need to dig deeper how to solve it in not-root mode.
